title: Enable
description: A sole-trader research and development venture dedicated to technology innovation
baseurl: "/enable"
url: "https://grokkkjokkk.github.io"
markdown: kramdown
theme: null
plugins: []
